# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'LivoniaAdultGentleCare' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LivoniaAdultGentleCare
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'

  target 'LivoniaAdultGentleCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LivoniaAdultGentleCareUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
